name: 'GH Action - Test Run'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

env:
  DEPLOYMENT_ENV: test
  NODE_ENV: development
  CTF_CDA_ACCESS_TOKEN: ${{secrets.CTF_CDA_ACCESS_TOKEN}}
  CTF_CPA_ACCESS_TOKEN: ${{secrets.CTF_CPA_ACCESS_TOKEN}}
  CTF_SPACE_ID: ${{ secrets.CTF_SPACE_ID }}
  CTF_ENVIRONMENT_ID: master
  DEBUG_LEVEL: 2 # NOTE: increase this to get more log information


jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          changelist-id: 'changelist-pmrc-1'
          cache-dir-path: './.cache'
